
server:
  port: 8080
spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/search_engine?useSSL=false&requireSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: admin

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

indexing-settings:

  sites:
#    - url: https://volochek.life
#      name: Volochek
#    - url: https://dombulgakova.ru
#      name: Dombulgakova
    - url: https://www.radiodacha.ru/
      name: Radiodacha
#    - url: https://www.radiomv.ru
#      name: Radiomv
    - url: https://ipfran.ru
      name: Ipfran
    - url: https://www.svetlovka.ru
      name: Svetlovka
    - url: https://www.playback.ru
      name: PlayBack
#    - url: https://hackaday.com
#      name: Hackaday
