
server:
  port: 8080
spring:
  datasource:
    # Меняем драйвер на PostgreSQL
    driver-class-name: org.postgresql.Driver
    # Указываем правильный URL (порт 5432) и имя базы
    url: jdbc:postgresql://localhost:5432/search_engine
    username: postgres # Ваш логин от postgres (обычно postgres)
    password: your_password # ВАШ пароль, который вы задали при установке PostgreSQL
  jpa:
    hibernate:
      # меняем update на validate или none, так как таблицы теперь создает Liquibase
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    # Указываем путь к файлу миграций (его сейчас создадим)
    change-log: classpath:db/changelog/db.changelog-master.yaml

indexing-settings:

  sites:
#    - url: https://volochek.life
#      name: Volochek
#    - url: https://dombulgakova.ru
#      name: Dombulgakova
    - url: https://www.radiodacha.ru/
      name: Radiodacha
#    - url: https://www.radiomv.ru
#      name: Radiomv
    - url: https://ipfran.ru
      name: Ipfran
    - url: https://www.svetlovka.ru
      name: Svetlovka
    - url: https://www.playback.ru
      name: PlayBack
#    - url: https://hackaday.com
#      name: Hackaday
